In [1]:
from joblib import load
import joblib
import pandas as pd
from datetime import datetime
import numpy as np

In [2]:
df = pd.read_excel("AKModeltesst_RE_raw export.xlsx")

In [3]:
df.shape

(46, 48)

In [4]:
details = df[['Domain', 'Name', 'Description', 'LinkedIn', 'Employee Estimate','Employee Growth (6 months)', 'Employee Growth (Annual)', 'Headquarters', 'Year Founded', 'Last Funding Amount', 'Last Funding Date', 'Total Funding Amount', 'Total Funding Rounds']]

In [5]:
data = df[['Employee Estimate', 'Employees on Professional Networks', 'Employee Growth (Monthly)', 'Employee Growth (Quarterly)', 'Employee Growth (6 months)', 'Employee Growth (Annual)', 'Headquarters', 'Year Founded', 'Last Funding Amount', 'Last Funding Date', 'Total Funding Amount', 'Total Funding Rounds', 'Business Model', 'Last Touch Date', 'Last Pipeline Decline Date']]

In [6]:
data

,Employee Estimate,Employees on Professional Networks,Employee Growth (Monthly),Employee Growth (Quarterly),Employee Growth (6 months),Employee Growth (Annual),Headquarters,Year Founded,Last Funding Amount,Last Funding Date,Total Funding Amount,Total Funding Rounds,Business Model,Last Touch Date,Last Pipeline Decline Date
0,237,236,0.43%,2.61%,8.26%,11.85%,"New York, NY",2015,50000000.0,2022-04-25,111970000.0,5.0,Software,NaN,NaN
1,218,73,8.96%,30.36%,55.32%,82.50%,"San Francisco, CA",2016,NaN,2022-10-27,2700000.0,5.0,Marketplace,2024-06-15T12:54:39.000+0000,NaN
2,199,393,2.34%,2.34%,5.36%,62.40%,"New York, NY",2017,4000000.0,2023-06-06,141040000.0,7.0,Software,NaN,NaN
3,185,308,1.65%,0.33%,0.98%,-3.45%,"San Francisco, CA",2012,80000000.0,2021-11-23,123550000.0,7.0,Software,2024-06-22T12:15:24.000+0000,NaN
4,183,183,-1.08%,0.55%,-5.18%,-3.68%,"Missouri, USA",2014,NaN,NaN,NaN,NaN,Software,NaN,NaN
5,167,169,1.81%,4.97%,9.74%,40.83%,"Boston, MA",2015,15000000.0,2022-10-04,24500000.0,4.0,Software,2024-06-22T12:15:51.000+0000,NaN
6,163,163,0.62%,1.87%,0.62%,10.14%,"Reston, VA",2009,NaN,NaN,NaN,5.0,Software,NaN,NaN
7,161,160,-3.03%,-5.33%,-11.60%,-22.71%,"San Francisco, CA",2012,30000000.0,2022-01-27,173060000.0,8.0,Software,NaN,NaN
8,140,141,-2.76%,-2.76%,-4.73%,-5.37%,"Blue Ash, OH",2010,17000000.0,2022-03-11,26980000.0,4.0,Software,2024-06-22T12:15:05.000+0000,NaN
9,124,124,0,-0.80%,0,14.81%,"New York, NY",1999,NaN,2022-07-14,NaN,1.0,Software,NaN,NaN
10,124,125,-0.79%,-3.10%,-4.58%,-10.71%,"Carlsbad, CA",2014,10000000.0,2020-04-21,22700000.0,3.0,Software,2024-06-15T12:49:23.000+0000,NaN
11,114,115,-4.96%,-2.54%,4.55%,16.16%,"New York, NY",2018,64000000.0,2023-10-27,93100000.0,6.0,Software,2024-06-22T12:17:19.000+0000,NaN
12,113,113,-0.88%,-1.74%,3.67%,14.14%,"Perth, Australia",2017,38000000.0,2022-12-14,69000000.0,5.0,NaN,2024-07-13T22:55:13.000+0000,NaN
13,106,106,1.92%,1.92%,7.07%,3.92%,"West Palm Beach, FL",2016,41000000.0,2020-10-21,41000000.0,1.0,Software,NaN,NaN
14,102,103,-1.90%,3.00%,13.19%,83.93%,"Princeton, NJ",2020,NaN,2021-04-20,NaN,1.0,Software,2024-07-15T03:16:55.000+0000,2024-03-06
15,101,101,-8.18%,-15.13%,-24.63%,-30.34%,"New York, NY",2016,16300000.0,2023-07-18,78770000.0,8.0,Software,NaN,NaN
16,93,93,-6.06%,-4.12%,-4.12%,-4.12%,"Menlo Park, CA",2013,13000000.0,2023-04-11,68349999.0,7.0,Software,NaN,NaN
17,88,89,2.30%,0,-2.20%,4.71%,"Dallas, TX",2013,52000000.0,2021-02-03,63700000.0,6.0,Software,NaN,NaN
18,74,74,-3.90%,-10.84%,-14.94%,-27.45%,"San Francisco, CA",2016,NaN,2023-03-08,50930000.0,8.0,Software,2024-07-13T22:56:13.000+0000,NaN
19,62,63,0,6.78%,12.50%,21.15%,"Fort Collins, CO",2015,6500000.0,2019-07-17,10450000.0,4.0,Software,NaN,NaN
20,61,62,-4.62%,-4.62%,-8.82%,-8.82%,"St. Charles, MO",2018,4000000.0,2021-10-07,7000000.0,4.0,Software,NaN,NaN
21,53,53,-1.85%,0,-3.64%,-11.67%,"New York, NY",2017,14000000.0,2023-10-24,30760000.0,6.0,Software,2024-06-22T12:17:17.000+0000,NaN
22,50,50,0,-1.96%,-1.96%,-1.96%,"Boston, MA",1987,NaN,NaN,NaN,NaN,Services,NaN,NaN
23,49,82,0,6.49%,18.84%,12.33%,"San Francisco, CA",2019,40000000.0,2022-07-13,54900000.0,4.0,Software,2024-07-13T22:52:31.000+0000,2024-07-02
24,49,91,2.25%,2.25%,8.33%,-23.53%,"Boston, MA",2017,NaN,2023-10-24,4030000.0,5.0,Software,2024-07-13T22:46:25.000+0000,2022-11-09
25,48,49,8.89%,4.26%,2.08%,11.36%,"California, USA",2015,9000000.0,2022-01-18,11580000.0,5.0,Software,2024-06-24T20:39:46.000+0000,NaN
26,46,96,1.05%,-2.04%,-8.57%,-10.28%,"San Francisco, CA",2014,43000000.0,2022-09-08,57760000.0,8.0,Software,2024-06-22T12:15:24.000+0000,NaN
27,46,80,-1.23%,1.27%,6.67%,5.26%,"Reston, VA",2011,NaN,NaN,NaN,0.0,Software,NaN,NaN
28,46,125,-2.34%,0,-3.10%,4.17%,"Mastic, NY",2014,125000000.0,2022-03-08,219580000.0,7.0,Software,2024-06-22T12:17:14.000+0000,NaN
29,45,45,-4.26%,-4.26%,4.65%,7.14%,"Washington, Washington, DC",2013,10000000.0,2022-06-01,16200000.0,4.0,Software,2024-06-20T15:25:38.000+0000,NaN
30,44,44,-4.35%,-6.38%,-8.33%,4.76%,"San Francisco, CA",2012,NaN,2016-09-27,NaN,1.0,Software,2024-07-10T01:33:09.000+0000,NaN
31,38,39,0,2.63%,0,-7.14%,"New York, NY",2016,NaN,2019-01-31,3260000.0,3.0,Software,2024-06-22T12:17:36.000+0000,NaN
32,36,37,-5.13%,2.78%,2.78%,-13.95%,"San Diego, CA",2016,12700000.0,2022-11-15,12700000.0,2.0,Software,2024-07-13T22:57:09.000+0000,2022-11-16
33,34,35,0,6.06%,9.38%,-2.78%,"New York, NY",2018,8000000.0,2021-04-29,10650000.0,4.0,Software,2024-06-22T12:16:54.000+0000,NaN
34,32,33,-8.33%,-10.81%,-15.38%,-13.16%,"Hawthorne, NY",2015,3150000.0,2022-05-03,3400000.0,5.0,Software,2024-07-13T22:52:31.000+0000,2024-04-11
35,29,30,3.45%,11.11%,30.43%,76.47%,"San Francisco, CA",2020,NaN,2022-01-01,130000.0,3.0,Software,2024-07-11T15:05:21.000+0000,2024-05-09
36,29,30,3.45%,0,-9.09%,-23.08%,"San Diego, CA",2018,15000000.0,2021-06-08,23750000.0,5.0,Software,NaN,NaN
37,27,27,-3.57%,-6.90%,-15.62%,-37.21%,"New York, NY",2020,20000000.0,2021-05-25,20000000.0,1.0,Software Enabled,NaN,NaN
38,23,23,15.00%,15.00%,15.00%,25.00%,"New York, NY",2022,8000000.0,2023-10-31,8000000.0,2.0,Software,2024-06-15T12:53:27.000+0000,NaN
39,22,23,-4.17%,9.52%,0,0,"Scottsdale, AZ",2005,NaN,NaN,NaN,0.0,Software,NaN,NaN
40,21,22,-4.35%,4.76%,-4.35%,-4.35%,"Miami, FL",2016,100000.0,2023-02-01,1110000.0,3.0,Software,2024-06-22T12:18:07.000+0000,NaN
41,21,21,-4.55%,-4.55%,-4.55%,-12.50%,"New York, NY",2020,8000000.0,2021-10-04,8000000.0,1.0,Software,2024-06-15T12:54:04.000+0000,NaN
42,18,19,0,-5.00%,11.76%,5.56%,"Chicago, IL",2011,NaN,2014-04-21,NaN,1.0,Software,NaN,NaN
43,16,16,-5.88%,-11.11%,-5.88%,-11.11%,"New York, NY",2017,150000.0,2021-01-28,150000.0,1.0,Software,2024-06-15T12:54:04.000+0000,NaN
44,15,15,25.00%,15.38%,0,7.14%,"Huntington Beach, CA",2022,4000000.0,2023-05-31,4000000.0,1.0,Software,2024-06-15T12:54:08.000+0000,NaN
45,11,7,-12.50%,-22.22%,0,-22.22%,"Myrtle Beach, SC",2016,120000.0,2020-09-08,470000.0,4.0,Services,NaN,NaN

In [7]:
import pandas as pd
import numpy as np
from datetime import datetime

# Assuming 'data' is your input DataFrame for predictions

# US location check
us_states = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']
data['is_us'] = data['Headquarters'].apply(lambda x: 0.5 if pd.isna(x) else int(any(state in x for state in us_states)))

# Calculate company age
current_year = datetime.now().year
data['company_age'] = current_year - data['Year Founded']

# Check for tech-enabled sectors
tech_enabled_sectors = ['Software', 'Software Enabled', 'Tech', 'Technology']
data['is_tech_enabled'] = data['Business Model'].apply(lambda x: 0 if pd.isna(x) else int(x in tech_enabled_sectors))

# Convert 'Employee Growth' columns to float
growth_columns = ['Employee Growth (Monthly)', 'Employee Growth (Quarterly)', 'Employee Growth (6 months)', 'Employee Growth (Annual)']
for col in growth_columns:
    data[col] = data[col].str.replace('%', '').astype(float)

# Process date columns
today = pd.Timestamp.now().tz_localize(None)
date_columns = ['Last Funding Date', 'Last Touch Date', 'Last Pipeline Decline Date']
for col in date_columns:
    data[col] = pd.to_datetime(data[col], errors='coerce').dt.tz_localize(None)
    data[f'Days Since {col}'] = (today - data[col]).dt.days

# Drop unnecessary columns
columns_to_drop = ['Headquarters', 'Year Founded', 'Business Model'] + date_columns
data = data.drop(columns=columns_to_drop)

/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['is_us'] = data['Headquarters'].apply(lambda x: 0.5 if pd.isna(x) else int(any(state in x for state in us_states)))
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['company_age'] = current_year - data['Year Founded']
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['is_tech_enabled'] = data['Business Model'].apply(lambda x: 0 if pd.isna(x) else int(x in tech_enabled_sectors))
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = data[col].str.replace('%', '').astype(float)
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = data[col].str.replace('%', '').astype(float)
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = data[col].str.replace('%', '').astype(float)
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = data[col].str.replace('%', '').astype(float)
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = pd.to_datetime(data[col], errors='coerce').dt.tz_localize(None)
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'Days Since {col}'] = (today - data[col]).dt.days
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = pd.to_datetime(data[col], errors='coerce').dt.tz_localize(None)
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'Days Since {col}'] = (today - data[col]).dt.days
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = pd.to_datetime(data[col], errors='coerce').dt.tz_localize(None)
/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/1548002739.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[f'Days Since {col}'] = (today - data[col]).dt.days

In [8]:
loaded_model = load('model_cb.joblib')

In [9]:
predictions = loaded_model.predict(data)
predictions += 1

In [10]:
data

,Employee Estimate,Employees on Professional Networks,Employee Growth (Monthly),Employee Growth (Quarterly),Employee Growth (6 months),Employee Growth (Annual),Last Funding Amount,Total Funding Amount,Total Funding Rounds,is_us,company_age,is_tech_enabled,Days Since Last Funding Date,Days Since Last Touch Date,Days Since Last Pipeline Decline Date
0,237,236,0.43,2.61,8.26,11.85,50000000.0,111970000.0,5.0,1,9,1,820.0,NaN,NaN
1,218,73,8.96,30.36,55.32,82.50,NaN,2700000.0,5.0,1,8,0,635.0,38.0,NaN
2,199,393,2.34,2.34,5.36,62.40,4000000.0,141040000.0,7.0,1,7,1,413.0,NaN,NaN
3,185,308,1.65,0.33,0.98,-3.45,80000000.0,123550000.0,7.0,1,12,1,973.0,31.0,NaN
4,183,183,-1.08,0.55,-5.18,-3.68,NaN,NaN,NaN,0,10,1,NaN,NaN,NaN
5,167,169,1.81,4.97,9.74,40.83,15000000.0,24500000.0,4.0,1,9,1,658.0,31.0,NaN
6,163,163,0.62,1.87,0.62,10.14,NaN,NaN,5.0,1,15,1,NaN,NaN,NaN
7,161,160,-3.03,-5.33,-11.60,-22.71,30000000.0,173060000.0,8.0,1,12,1,908.0,NaN,NaN
8,140,141,-2.76,-2.76,-4.73,-5.37,17000000.0,26980000.0,4.0,1,14,1,865.0,31.0,NaN
9,124,124,NaN,-0.80,NaN,14.81,NaN,NaN,1.0,1,25,1,740.0,NaN,NaN
10,124,125,-0.79,-3.10,-4.58,-10.71,10000000.0,22700000.0,3.0,1,10,1,1554.0,38.0,NaN
11,114,115,-4.96,-2.54,4.55,16.16,64000000.0,93100000.0,6.0,1,6,1,270.0,31.0,NaN
12,113,113,-0.88,-1.74,3.67,14.14,38000000.0,69000000.0,5.0,0,7,0,587.0,9.0,NaN
13,106,106,1.92,1.92,7.07,3.92,41000000.0,41000000.0,1.0,1,8,1,1371.0,NaN,NaN
14,102,103,-1.90,3.00,13.19,83.93,NaN,NaN,1.0,1,4,1,1190.0,8.0,139.0
15,101,101,-8.18,-15.13,-24.63,-30.34,16300000.0,78770000.0,8.0,1,8,1,371.0,NaN,NaN
16,93,93,-6.06,-4.12,-4.12,-4.12,13000000.0,68349999.0,7.0,1,11,1,469.0,NaN,NaN
17,88,89,2.30,NaN,-2.20,4.71,52000000.0,63700000.0,6.0,1,11,1,1266.0,NaN,NaN
18,74,74,-3.90,-10.84,-14.94,-27.45,NaN,50930000.0,8.0,1,8,1,503.0,9.0,NaN
19,62,63,NaN,6.78,12.50,21.15,6500000.0,10450000.0,4.0,1,9,1,1833.0,NaN,NaN
20,61,62,-4.62,-4.62,-8.82,-8.82,4000000.0,7000000.0,4.0,1,6,1,1020.0,NaN,NaN
21,53,53,-1.85,NaN,-3.64,-11.67,14000000.0,30760000.0,6.0,1,7,1,273.0,31.0,NaN
22,50,50,NaN,-1.96,-1.96,-1.96,NaN,NaN,NaN,1,37,0,NaN,NaN,NaN
23,49,82,NaN,6.49,18.84,12.33,40000000.0,54900000.0,4.0,1,5,1,741.0,9.0,21.0
24,49,91,2.25,2.25,8.33,-23.53,NaN,4030000.0,5.0,1,7,1,273.0,9.0,622.0
25,48,49,8.89,4.26,2.08,11.36,9000000.0,11580000.0,5.0,0,9,1,917.0,28.0,NaN
26,46,96,1.05,-2.04,-8.57,-10.28,43000000.0,57760000.0,8.0,1,10,1,684.0,31.0,NaN
27,46,80,-1.23,1.27,6.67,5.26,NaN,NaN,0.0,1,13,1,NaN,NaN,NaN
28,46,125,-2.34,NaN,-3.10,4.17,125000000.0,219580000.0,7.0,1,10,1,868.0,31.0,NaN
29,45,45,-4.26,-4.26,4.65,7.14,10000000.0,16200000.0,4.0,0,11,1,783.0,32.0,NaN
30,44,44,-4.35,-6.38,-8.33,4.76,NaN,NaN,1.0,1,12,1,2856.0,13.0,NaN
31,38,39,NaN,2.63,NaN,-7.14,NaN,3260000.0,3.0,1,8,1,2000.0,31.0,NaN
32,36,37,-5.13,2.78,2.78,-13.95,12700000.0,12700000.0,2.0,1,8,1,616.0,9.0,615.0
33,34,35,NaN,6.06,9.38,-2.78,8000000.0,10650000.0,4.0,1,6,1,1181.0,31.0,NaN
34,32,33,-8.33,-10.81,-15.38,-13.16,3150000.0,3400000.0,5.0,1,9,1,812.0,9.0,103.0
35,29,30,3.45,11.11,30.43,76.47,NaN,130000.0,3.0,1,4,1,934.0,11.0,75.0
36,29,30,3.45,NaN,-9.09,-23.08,15000000.0,23750000.0,5.0,1,6,1,1141.0,NaN,NaN
37,27,27,-3.57,-6.90,-15.62,-37.21,20000000.0,20000000.0,1.0,1,4,1,1155.0,NaN,NaN
38,23,23,15.00,15.00,15.00,25.00,8000000.0,8000000.0,2.0,1,2,1,266.0,38.0,NaN
39,22,23,-4.17,9.52,NaN,NaN,NaN,NaN,0.0,1,19,1,NaN,NaN,NaN
40,21,22,-4.35,4.76,-4.35,-4.35,100000.0,1110000.0,3.0,1,8,1,538.0,31.0,NaN
41,21,21,-4.55,-4.55,-4.55,-12.50,8000000.0,8000000.0,1.0,1,4,1,1023.0,38.0,NaN
42,18,19,NaN,-5.00,11.76,5.56,NaN,NaN,1.0,1,13,1,3746.0,NaN,NaN
43,16,16,-5.88,-11.11,-5.88,-11.11,150000.0,150000.0,1.0,1,7,1,1272.0,38.0,NaN
44,15,15,25.00,15.38,NaN,7.14,4000000.0,4000000.0,1.0,1,2,1,419.0,38.0,NaN
45,11,7,-12.50,-22.22,NaN,-22.22,120000.0,470000.0,4.0,1,8,0,1414.0,NaN,NaN

In [11]:
predictions

array([ 3,  5,  2, 10,  3,  3, 10, 10, 10,  5,  7,  8,  8, 10,  4,  7,  2,
       10,  7,  5,  7,  7,  7,  6,  7, 10,  7,  6, 10, 10, 10,  7,  7,  7,
        7, 10,  7, 10,  8,  4,  7, 10,  4,  4,  8,  1])

In [12]:
details['score']=predictions

/var/folders/jz/27btwlsn5hj2km5hc3rg4vfr0000gn/T/ipykernel_4478/4281648696.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  details['score']=predictions

In [13]:
cols = details.columns.tolist()
cols = cols[-1:] + cols[:-1]
details = details[cols]

In [24]:
# Updating 'score' to 1 for specified conditions
details.loc[(details['Last Funding Amount'] > 40000000) | (details['Total Funding Amount'] > 150000000), 'score'] = 1

# Save to Excel without index
details.to_excel("final_output.xlsx", index=False)